name: Build and Deploy textcpp

on:
  push:
    branches: [ master ]
    tags: 
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4.9.1
      with:
        python-version: '3.12'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pybind11 twine

    - name: Build package
      run: python -m build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: textcpp-dist
        path: dist/*.tar.gz

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*.tar.gz
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: pypi-deploy

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: textcpp-dist

    - name: Upload only sdist to PyPI
      run: |
          python -m pip install twine
          python -m twine upload *.tar.gz
      env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
